Update bash script to fail if python script failed

diff --git a/pipelines/steps/get-synapse-details.yaml b/pipelines/steps/get-synapse-details.yaml
--- a/pipelines/steps/get-synapse-details.yaml
+++ b/pipelines/steps/get-synapse-details.yaml
@@ -9,5 +9,9 @@ steps:
       python${{ parameters.pythonVersion }} --version
       export PYTHONPATH="${PYTHONPATH}:/./"
       python${{ parameters.pythonVersion }} $(System.DefaultWorkingDirectory)/pipelines/scripts/get_synapse_details.py --env ${{ parameters.env }} --failover_deployment ${{ parameters.failoverDeployment }}
+      if [ $? -eq 1 ] then
+          echo "##vso[task.logissue type=error]get_synapse_details.py failed"
+          exit 1
+      fi
     displayName: 'Set Variables'
     name: SetVariables
