Convert job to step

diff --git a/pipelines/dev-synapse-pr.yaml b/pipelines/dev-synapse-pr.yaml
--- a/pipelines/dev-synapse-pr.yaml
+++ b/pipelines/dev-synapse-pr.yaml
@@ -15,28 +15,33 @@ variables:
   #  env: prod
   ${{ else }}:
     env: null
+  agentPool: 'pins-agent-pool-odw-${{ variables.env }}-uks'
 
 stages:
 - stage: validateBuildBranch
   displayName: 'Check that the build branch is correct'
-  steps:
-  - task: AzureCLI@2
-    displayName: 'Fail pipeline'
-    condition: eq(variables.env, null)
-    inputs:
-      azureSubscription: 'ODW ${{ upper(parameters.env) }} - Infrastructure'
-      scriptType: bash
-      scriptLocation: inlineScript
-      inlineScript: |
-        echo "##vso[task.logissue type=error]The pipeline can only run against the following branches ['dev', 'testing', 'main'] but tried to run against variables['Build.SourceBranch']"
-        exit 1
+  jobs:
+  - job: validateBuildBranchJob
+    displayName: Check that the build branch is correct
+    pool: ${{ variables.agentPool }}
+    steps:
+    - task: AzureCLI@2
+      displayName: 'Fail pipeline'
+      condition: eq(variables.env, null)
+      inputs:
+        azureSubscription: 'ODW ${{ upper(parameters.env) }} - Infrastructure'
+        scriptType: bash
+        scriptLocation: inlineScript
+        inlineScript: |
+          echo "##vso[task.logissue type=error]The pipeline can only run against the following branches ['dev', 'testing', 'main'] but tried to run against variables['Build.SourceBranch']"
+          exit 1
 - stage: DeploySynapse
   # This needs to be updated to deploy to the build environment once that has been created
   displayName: 'Deploy Synapse to the ${{ variables.env }} environment'
   jobs:
   - template: jobs/deploy-synapse.yaml
     parameters:
-      agentPool: 'pins-agent-pool-odw-${{ variables.env }}-uks'
+      agentPool: ${{ variables.agentPool }}
       env: ${{ variables.env }}
       activateTriggers: false
       runUnitTests: true
