Fix syntax error

diff --git a/pipelines/dev-synapse-pr.yaml b/pipelines/dev-synapse-pr.yaml
--- a/pipelines/dev-synapse-pr.yaml
+++ b/pipelines/dev-synapse-pr.yaml
@@ -20,9 +20,16 @@ stages:
 - stage: validateBuildBranch
   displayName: 'Check that the build branch is correct'
   jobs:
-  - script: |
-      echo "##vso[task.logissue type=error]The pipeline can only run against the following branches ['dev', 'testing', 'main'] but tried to run against variables['Build.SourceBranch']"
-      exit 1
+  - task: AzureCLI@2
+    displayName: 'Fail pipeline'
+    condition: eq(variables.env, null)
+    inputs:
+      azureSubscription: 'ODW ${{ upper(parameters.env) }} - Infrastructure'
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        echo "##vso[task.logissue type=error]The pipeline can only run against the following branches ['dev', 'testing', 'main'] but tried to run against variables['Build.SourceBranch']"
+        exit 1
     condition: eq(variables.env, null)
 - stage: DeploySynapse
   # This needs to be updated to deploy to the build environment once that has been created
